import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa.d3kq8oy4csoq2n.amplifyapp.com/');
  await page.getByTestId('SI-username-input-password').click();
  await page.getByTestId('SI-username-input-password').fill('9699342811+2');
  await page.getByTestId('SI-password-input-password').click();
  await page.getByTestId('SI-password-input-password').fill('Ritesh@123');
  await page.getByTestId('SI-submit-button-show').click();
  await page.getByTestId('menu-item-hostel').click();
  await page.getByTestId('submenu-item-memberships').click();
  await page.getByTestId('H-M-member-name-0').click();
  await page.getByRole('link', { name: 'Fees Details' }).click();
  await page.getByTestId('H-M-FD-Template-Search-Toggle').click();
  await page.getByText('bhushan raut').click();
  await page.getByTestId('H-M-FD-Template-Add-Button').click();
  await page.getByTestId('H-M-FD-FeeTemplate-Add-Installment-Button').click();
  await page.getByTestId('H-M-FD-FeeTemplate-Installment-Amount-Input-0').click();
  await page.getByTestId('H-M-FD-FeeTemplate-Installment-Amount-Input-0').fill('30');
  await page.getByRole('textbox', { name: 'Select date' }).click();
  await page.getByRole('button', { name: '31' }).click();
  await page.getByTestId('H-M-FD-FeeTemplate-Save-All-Button').click();

await page.locator('.lucide.lucide-chevron-down').first().click();
  await page.locator('.lucide.lucide-chevron-down').first().click();
  await page.getByTestId('H-M-FD-Get-Payment-Button-0-0').click();


  await page.getByRole('checkbox', { name: 'Manual Payment' }).check();
  await page.getByRole('textbox', { name: 'Select date' }).click();
  await page.getByRole('button', { name: '31' }).click();
  await page.getByRole('textbox', { name: 'Enter Transaction ID' }).click();
  await page.getByRole('textbox', { name: 'Enter Transaction ID' }).fill('12522996');
  await page.getByRole('button', { name: 'Select Provider' }).click();
  await page.getByText('smart').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.ml-2 > .lucide').first().click();
  await page.locator('.lucide.lucide-chevron-up').click();
  await page.getByRole('link', { name: 'Personal Details' }).click();
  await page.getByTestId('H-M-PD-Edit-Button').click();
  await page.getByTestId('H-M-PD-Perm-HouseNo-Input').click();
  await page.getByTestId('H-M-PD-Perm-HouseNo-Input').fill('20');
  await page.getByTestId('H-M-PD-Perm-Street-Input').click();
  await page.getByTestId('H-M-PD-Perm-Street-Input').fill('no');
  await page.getByTestId('H-M-PD-Perm-Locality-Input').click();
  await page.getByTestId('H-M-PD-Perm-Locality-Input').fill('no');
  await page.getByTestId('H-M-PD-Perm-State-Input').click();
  await page.getByTestId('H-M-PD-Perm-State-Input').fill('no');
  await page.getByTestId('H-M-PD-Perm-City-Input').click();
  await page.getByTestId('H-M-PD-Perm-City-Input').fill('no');
  await page.getByTestId('H-M-PD-Temp-City-Input').click();
  await page.getByTestId('H-M-PD-Temp-City-Input').fill('no');
  await page.getByTestId('H-M-PD-Temp-State-Input').click();
  await page.getByTestId('H-M-PD-Temp-State-Input').fill('no');
  await page.getByTestId('H-M-PD-Temp-Street-Input').click();
  await page.getByTestId('H-M-PD-Temp-Street-Input').fill('no');
  await page.getByTestId('H-M-PD-Temp-HouseNo-Input').click();
  await page.getByTestId('H-M-PD-Temp-HouseNo-Input').fill('20');
  await page.getByTestId('H-M-PD-Temp-Village-Input').click();
  await page.getByTestId('H-M-PD-Temp-Village-Input').fill('no');
  await page.getByTestId('H-M-PD-Temp-Locality-Input').click();
  await page.getByTestId('H-M-PD-Temp-Locality-Input').fill('no');
  await page.getByTestId('H-M-PD-Temp-ZipCode-Input').click();
  await page.getByTestId('H-M-PD-Temp-ZipCode-Input').fill('232334');
  await page.getByTestId('H-M-PD-Temp-Country-Dropdown').click();
  await page.getByTestId('H-M-PD-Temp-Country-Option-India').click();
  await page.getByTestId('H-M-PD-Perm-ZipCode-Input').click();
  await page.getByTestId('H-M-PD-Perm-ZipCode-Input').fill('223212');
  await page.getByTestId('H-M-PD-Perm-Country-Dropdown').click();
  await page.getByTestId('H-M-PD-Perm-Country-Option-India').click();
  await page.getByTestId('H-M-PD-Family-Name-Input-0').click();
  await page.getByTestId('H-M-PD-Family-Name-Input-0').fill('efewfwef');
  await page.getByTestId('H-M-PD-Family-Email-Input-0').click();
  await page.getByTestId('H-M-PD-Family-Email-Input-0').fill('hjfhbejhf123@gmail.com');
  await page.getByTestId('H-M-PD-Family-Phone-Input-0').click();
  await page.getByTestId('H-M-PD-Family-Phone-Input-0').fill('2345654345');
  await page.getByTestId('H-M-PD-Emergency-Name-Input-0').click();
  await page.getByTestId('H-M-PD-Emergency-Name-Input-0').fill('rfwfwfw');
  await page.getByTestId('H-M-PD-Emergency-Relation-Input-0').click();
  await page.getByTestId('H-M-PD-Emergency-Relation-Input-0').fill('grgrgrg');
  await page.getByTestId('H-M-PD-Emergency-Phone-Input-0').click();
  await page.getByTestId('H-M-PD-Emergency-Phone-Input-0').fill('2453454252');
  await page.getByTestId('H-M-PD-Save-Button').click();
  await page.getByTestId('H-M-AD-Back-Button').click();
  await page.getByTestId('H-M-exit-member-0').click();
  await page.getByTestId('H-M-exit-confirm-button').click();
});
