import { test, expect } from '@playwright/test';

test('Hostel - Create building/floor/room/template/member with unique data', async ({ page }) => {
  // प्रत्येक run ला वेगळा suffix - duplicate data टाळण्यासाठी
  const uniqueId = Date.now();
  const buildingName = `rox building ${uniqueId}`;
  const floorName = `rox floor ${uniqueId}`;
  const roomName = `rox room ${uniqueId}`;
  const templateName = `rox template ${uniqueId}`;
  const componentName = `rozz ${uniqueId}`;

  await page.goto('https://qa.d3kq8oy4csoq2n.amplifyapp.com/');
  await page.getByTestId('SI-username-input-password').click();
  await page.getByTestId('SI-username-input-password').fill('9699342811+2');
  await page.getByTestId('SI-password-input-password').click();
  await page.getByTestId('SI-password-input-password').fill('Ritesh@123');
  await page.getByTestId('SI-submit-button-show').click();
  await page.getByTestId('menu-item-hostel').click();
  await page.getByTestId('submenu-item-premises').click();
  await page.getByTestId('H-P-B-building-button').click();
  await page.getByTestId('H-P-B-Add-Building-Name').click();
  await page.getByTestId('H-P-B-Add-Building-Name').fill(buildingName);
  await page.getByText('Select Type').click();
  await page.getByTestId('H-P-B-Add-Type').getByText('Room').click();
  await page.getByTestId('H-P-B-Add-Capacity').click();
  await page.getByTestId('H-P-B-Add-Capacity').fill('5');
  await page.getByTestId('H-P-B-Add-Address').click();
  await page.getByTestId('H-P-B-Add-Address').fill('talegon dighe');
  await page.getByTestId('H-P-B-Add-Location').click();
  await page.getByText('Baap company').nth(1).click();
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: 'Bhushan Rahut' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByTestId('H-HP-Tab-Link-floor').click();
  await page.getByTestId('H-P-F-add-floor-button').click();
  await page.getByTestId('H-P-F-Add-Floor-Name').click();
  await page.getByTestId('H-P-F-Add-Floor-Name').fill(floorName);
  await page.getByTestId('H-P-F-Add-Capacity').click();
  await page.getByTestId('H-P-F-Add-Capacity').fill('2');
  await page.locator('.react-select__input-container').click();
  await page.getByRole('option', { name: `${buildingName} (Baap company)` }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByTestId('H-HP-Tab-Link-room').click();
  await page.getByTestId('H-P-R-add-room-button').click();
  await page.getByTestId('H-P-R-Add-Room-Name').click();
  await page.getByTestId('H-P-R-Add-Room-Name').fill(roomName);
  await page.locator('.react-select__input-container').first().click();
  await page.getByText(`${buildingName} (Baap company)`).click();
  await page.getByTestId('H-P-R-Add-room-capacity').click();
  await page.getByTestId('H-P-R-Add-room-capacity').fill('2');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByTestId('submenu-item-hostel-fees-template').click();
  await page.getByTestId('H-HFT-add-hostel-template-button').click();
  await page.getByTestId('H-HFT-Add-name-input').click();
  await page.getByTestId('H-HFT-Add-name-input').fill(templateName);
  await page.getByTestId('H-HFT-Add-payment-types-dropdown').getByText('Select Payment Types').click();
  await page.locator('div').filter({ hasText: /^smart$/ }).nth(1).click();
  await page.locator('.w-4').first().click();
  await page.getByTestId('H-HFT-Add-add-component-button').click();
  await page.getByTestId('H-HFT-Add-block-name-input-0').click();
  await page.getByTestId('H-HFT-Add-block-name-input-0').fill(componentName);
  await page.getByTestId('H-HFT-Add-block-Amount-input-0').click();
  await page.getByTestId('H-HFT-Add-block-Amount-input-0').fill('3000');
  await page.getByTestId('H-HFT-Add-add-component-button-0').click();
  await page.getByTestId('H-HFT-Add-save-button').click();
  await page.getByTestId('submenu-item-memberships').click();
  await page.getByTestId('H-M-add-member-button').click();
  await page.locator('.react-select__input-container').first().click();
  await page.locator('#react-select-6-option-0').click();
  await page.locator('.react-select__control.css-ku5mul-control > .react-select__value-container > .react-select__input-container').first().click();
  await page.getByRole('option', { name: buildingName }).click();
  await page.getByRole('textbox', { name: 'Select date' }).first().click();
  await page.getByRole('button', { name: '1' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Select date' }).nth(1).click();
  await page.getByRole('button', { name: '13', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByTestId('submenu-item-hostel-attendance').click();
  await page.getByTestId('submenu-item-gatepass-requests').click();
  await page.getByTestId('submenu-item-gatepass-request-approvals').click();
});