import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa.d3kq8oy4csoq2n.amplifyapp.com/');
  await page.getByTestId('SI-username-input-password').click();
  await page.getByTestId('SI-username-input-password').fill('swati.dighe@gmail.com');
  await page.getByTestId('SI-username-input-password').press('Enter');
  await page.getByTestId('SI-password-input-password').fill('Swati@123');
  await page.getByTestId('SI-submit-button-show').click();
  await page.getByTestId('CG-org-name-571bf643-60d5-4e9c-9c99-b8a52ca1832a').click();
  await page.getByRole('button', { name: 'Admission & Fees' }).click();
  await page.getByRole('link', { name: 'Admissions' }).click();
  await page.getByTestId('AF-add-admission-button').click();
  await page.getByTestId('AF-student-prn-input').click();
  await page.getByTestId('AF-student-prn-input').fill('8765');
  await page.getByTestId('AF-student-title-dropdown').click();
  await page.getByText('Mr', { exact: true }).click();
  await page.getByTestId('AF-student-first-name').click();
  await page.getByTestId('AF-student-first-name').fill('sam');
  await page.getByTestId('AF-student-last-name').click();
  await page.getByTestId('AF-student-last-name').fill('navle');
  await page.getByTestId('AF-student-gender-dropdown').click();
  await page.getByTestId('AF-student-gender-options').locator('div').filter({ hasText: /^Male$/ }).click();
  await page.locator('div').filter({ hasText: /^Date of Birth \*$/ }).click();
  await page.getByRole('textbox', { name: 'Select date' }).click();
  await page.getByRole('textbox', { name: 'Select date' }).click();
  await page.getByRole('button', { name: '8', exact: true }).click();
  await page.getByTestId('AF-student-location-textbox').click();
  await page.getByTestId('AF-student-location-input').getByText('Baap company').click();
  await page.getByTestId('student-email').click();
  await page.getByTestId('student-email').fill('sam123@gmail.com');
  await page.locator('.h-\\[40px\\].w-\\[60px\\]').first().click();
  await page.getByTestId('AF-student-phone').click();
  await page.getByTestId('AF-student-phone').fill('3456787654');
  await page.locator('.h-\\[40px\\].w-\\[60px\\] > .text-\\[var\\(--text-color\\)\\] > path').click();
  await page.locator('.css-1995squ-control > .css-hlgwow > .css-15ol6m4').first().click();
  await page.getByRole('option', { name: 'BCA' }).click();
  await page.locator('.css-1995squ-control > .css-hlgwow > .css-15ol6m4').first().click();
  await page.getByRole('option', { name: 'second year' }).click();
  await page.getByTestId('AF-student-save-button').click();
});