// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('https://qa.d3kq8oy4csoq2n.amplifyapp.com/');
//   await page.getByTestId('SI-username-input-password').click();
//   await page.getByTestId('SI-username-input-password').fill('9699342811+2');
//   await page.getByTestId('SI-password-input-password').click();
//   await page.getByTestId('SI-password-input-password').fill('Ritesh@123');
//   await page.getByTestId('SI-submit-button-show').click();
//   await page.getByRole('button', { name: 'Admission & Fees' }).click();
//   await page.getByRole('link', { name: 'Admissions' }).click();
//  await page.getByText('Mr. Ram Sham').first().click();  
//   await page.getByTestId('AI-PD-edit-contact-info-button').click();
//   await page.getByTestId('AI-PD-permanent-zip-code-input').click();
//   await page.getByTestId('AI-PD-permanent-zip-code-input').fill('422611');
//   await page.getByTestId('AI-PD-permanent-state-input').click();
//   await page.getByTestId('AI-PD-permanent-state-input').fill('MH');
//   await page.getByTestId('AI-PD-permanent-city-input').click();
//   await page.getByTestId('AI-PD-permanent-city-input').fill('sangamner');
//   await page.getByTestId('AI-PD-permanent-country-dropdown').getByText('Select Country').click();
//   await page.getByText('India').click();
//   await page.getByTestId('AI-PD-permanent-locality-input').click();
//   await page.getByTestId('AI-PD-permanent-locality-input').fill('low');
//   await page.getByTestId('AI-PD-permanent-street-input').click();
//   await page.getByTestId('AI-PD-permanent-street-input').fill('Mh');
//   await page.getByTestId('AI-PD-permanent-house-no-input').click();
//   await page.getByTestId('AI-PD-permanent-house-no-input').fill('house');
//   await page.getByTestId('AI-PD-permanent-village-input').click();
//   await page.getByTestId('AI-PD-permanent-village-input').fill('no');
//   await page.getByTestId('AI-PD-family-member-name-input-0').click();
//   await page.getByTestId('AI-PD-family-member-name-input-0').fill('somnath');
//   await page.getByTestId('AI-PD-family-member-email-input-0').click();
//   await page.getByTestId('AI-PD-family-member-email-input-0').fill('somnath12@gmail.com');
//   await page.getByTestId('AI-PD-family-member-phone-input-0').click();
//   await page.getByTestId('AI-PD-family-member-phone-input-0').fill('7656577878');
//   await page.getByTestId('AI-PD-family-member-whatsapp-checkbox-0').check();
//   await page.getByTestId('AI-PD-save-personal-details-button').click();
//   await page.getByText('Select Blood Group').click();
//   await page.getByText('A+').click();
//   await page.getByTestId('AI-PD-save-personal-details-button').click();
//   await page.getByTestId('EA-tab-academic-info').click();
//   await page.getByTestId('AI-A-edit-icon').click();
//   await page.getByTestId('AI-A-course-input').click();
//   await page.getByTestId('AI-A-class-input').click();
//   await page.getByTestId('AI-A-prn-no-input').click();
//   await page.getByTestId('AI-A-roll-no-input').click();
//   await page.getByTestId('AI-A-place-of-birth-input').click();
//   await page.getByTestId('AI-A-remote').check();
//   await page.getByTestId('AI-A-admission-executive-name').click();
//   await page.getByTestId('AI-A-admission-executive-phone').click();
//   await page.getByTestId('AI-A-custom-field-key-0').click();
//   await page.getByTestId('AI-A-custom-field-value-0').click();
//   await page.getByTestId('AI-A-save-button').click();
//   await page.getByTestId('EA-tab-notes').click();
//   await page.getByTestId('AI-N-title').click();
//   await page.getByTestId('AI-N-title').fill('boock');
//   await page.getByTestId('AI-N-description').click();
//   await page.getByTestId('AI-N-description').fill('no');
//   await page.getByTestId('AI-N-approver').click();
//   await page.getByTestId('AI-N-approver-dropdown').getByText('pankaj pawar').click();
//   await page.getByTestId('AI-N-date').click();
//   await page.getByRole('button', { name: '1', exact: true }).click();
//   await page.getByTestId('AI-N-save-btn').click();
//   await page.getByTestId('EA-back-button').click();
// });



import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa.d3kq8oy4csoq2n.amplifyapp.com/');
  await page.getByTestId('SI-username-input-password').click();
  await page.getByTestId('SI-username-input-password').fill('9699342811+2');
  await page.getByTestId('SI-password-input-password').click();
  await page.getByTestId('SI-password-input-password').fill('Ritesh@123');
  await page.getByTestId('SI-password-input-password').press('Enter');
  await page.getByTestId('menu-item-admission-&-fees').click();
  await page.getByTestId('submenu-item-admissions').click();
  await page.getByTestId('AF-add-admission-button').click();
  await page.getByTestId('AF-student-prn-input').click();
  await page.getByTestId('AF-student-prn-input').fill('6789');
  await page.getByTestId('AF-student-title-dropdown').click();
  await page.getByTestId('AF-student-title-option-Mr').click();
  await page.getByTestId('AF-student-first-name').click();
  await page.getByTestId('AF-student-first-name').fill('fghjhgfvghj');
  await page.getByTestId('AF-student-last-name').click();
  await page.getByTestId('AF-student-last-name').fill('fghbjhvbnm');
  await page.getByTestId('AF-student-gender-dropdown').click();
  await page.getByTestId('AF-student-gender-options').locator('div').filter({ hasText: /^Male$/ }).click();
  await page.getByTestId('AF-student-dob-input').click();
  await page.getByTestId('AF-student-dob-field').getByRole('button', { name: '1', exact: true }).click();
  await page.getByTestId('AF-student-location-textbox').click();
  await page.getByTestId('AF-student-location-option-ef8ffae7-1c54-4570-8027-02f35e8017bd').click();
  await page.locator('.css-1995squ-control > .css-hlgwow > .css-15ol6m4').first().click();
  await page.getByRole('option', { name: 'BCA' }).click();
  await page.locator('.css-1995squ-control > .css-hlgwow > .css-15ol6m4').first().click();
  await page.getByRole('option', { name: 'second year' }).click();
  await page.getByTestId('AF-student-save-button').click();
  await page.getByTestId('AF-close-student-sidebar').click();
  await page.getByTestId('AF-admission-name-15946b4a-02a5-42de-81c0-2de870e39cd6').getByText('Mr. Ram Sham').click();
  await page.getByTestId('EA-tab-fees-details').click();
  await page.getByTestId('AI-FD-template-select').click();
  await page.getByTestId('AI-FD-template-dropdown-list').getByText('sujit').click();
  await page.getByTestId('AI-FD-add-template').click();
  await page.getByTestId('AI-FD-add-installment').click();
  await page.getByTestId('AI-FD-installment-amount-input').click();
  await page.getByTestId('AI-FD-installment-amount-input').fill('300');
  await page.getByTestId('AI-FD-installment-dueon').click();
  await page.getByRole('button', { name: '24' }).click();
  await page.getByTestId('AI-FD-save-installments').click();
  await page.getByText('Sujit').click();
  await page.getByText('Installment', { exact: true }).click();
  await page.getByTestId('AI-FD-get-payment-btn-0-1').click();
  await page.getByTestId('AI-PAY-save-btn').first().click();
  await page.getByTestId('EA-back-button').click();
});