import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa.d3kq8oy4csoq2n.amplifyapp.com/');
  await page.getByRole('textbox', { name: 'Enter your email or phone' }).click();
  await page.getByRole('textbox', { name: 'Enter your email or phone' }).fill('9699342811+2');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ritesh@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Admission & Fees' }).click();
  await page.getByRole('link', { name: 'Admissions' }).click();
  await page.getByTestId('add-admission-button').click();
  await page.getByTestId('student-prn-input').click();
  await page.getByTestId('student-prn-input').fill('132');
  await page.getByRole('button', { name: 'Title' }).click();
  await page.getByText('Miss', { exact: true }).click();
  await page.getByTestId('student-first-name').click();
  await page.getByTestId('student-first-name').fill('nb vnmsdsdvvsd');
  await page.getByTestId('student-middle-name').click();
  await page.getByTestId('student-middle-name').fill('vsdsdf');
  await page.getByTestId('student-last-name').click();
  await page.getByTestId('student-middle-name').fill('vsdsdfs');
  await page.getByTestId('student-last-name').fill('fdsdvsd');
  await page.getByTestId('student-gender-dropdown').click();
  await page.locator('div').filter({ hasText: /^Male$/ }).click();
  await page.getByRole('textbox', { name: 'Select date' }).click();
  await page.getByRole('button', { name: '15' }).click();
  await page.getByRole('textbox', { name: 'Select location' }).click();
  await page.getByTestId('student-location-input').getByText('Baap company').click();
  await page.getByTestId('student-email').click();
  await page.getByTestId('student-email').fill('rautb8057@gmail.com');
  await page.getByTestId('student-phone').click();
  await page.getByTestId('student-phone').press('NumLock');
  await page.getByTestId('student-phone').fill('4567777654');
  await page.locator('.h-\\[40px\\].w-\\[60px\\] > .text-\\[var\\(--text-color\\)\\]').first().click();
  await page.locator('.h-\\[40px\\].w-\\[60px\\] > .text-\\[var\\(--text-color\\)\\] > path').click();
  await page.locator('.css-1995squ-control > .css-hlgwow > .css-15ol6m4').first().click();
  await page.getByRole('option', { name: 'BCA' }).click();
  await page.locator('.css-1995squ-control > .css-hlgwow > .css-15ol6m4').first().click();
  await page.getByRole('option', { name: 'second year' }).click();
  await page.getByTestId('student-save-button').click();
});